#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'dexbot==0.4.8','console_scripts','dexbot-cli'
__requires__ = 'dexbot==0.4.8'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('dexbot==0.4.8', 'console_scripts', 'dexbot-cli')()
    )
